apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - image: 108356037/tickets
        name: tickets
        env:
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-svc:27017/tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_URL
            value: 'http://nats-server-svc:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        imagePullPolicy: IfNotPresent
        resources: {}
      initContainers:
      - name: init-service
        image: busybox
        command: ['sh', '-c', "until nslookup tickets-mongo-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db setup; sleep 2; done"]
      # imagePullSecrets:
      # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-svc
spec:
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      