apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - image: 108356037/tickets
        name: tickets
        env:
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-svc:27017/tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        imagePullPolicy: IfNotPresent
        resources: {}
      # imagePullSecrets:
      # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-svc
spec:
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      